### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by lrhjw** [Mazin-Hnewa/MS-DAYOLO#1]
/usr/bin/ld can not find -lnppicom

env: cuda11.1 cudnn8.0

**Comment by Mazin-Hnewa** [comment]
Please check https://github.com/AlexeyAB/darknet  to install the required packages to compile Darknet.

**Comment by lrhjw** [comment]
I also install [AlexeyAB/darknet](https://github.com/AlexeyAB/darknet) by cmake . I also tried to use the cmake way in darnet  ,but it did not work.

**Comment by Mazin-Hnewa** [comment]
Did you successfully compile the original [AlexeyAB/darknet](https://github.com/AlexeyAB/darknet) and run YOLOv4?
if you did, you can successfully compile our code.

**Comment by lrhjw** [comment]
Thank you!  I have solved this problem.  I copy some file of cmake in darknet  and modify file in src/ . it has been compiled sucessfull by cmake.
Thanks very much.
